version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  build_deploy:
    docker:
      - image: cimg/node:22.9.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - gh-pages/deploy:
          ssh-fingerprints: '9b:f8:a1:6f:dc:1f:ab:99:f5:f5:92:b8:da:86:b3:ab'

workflows:
  Build and Deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
